### ISSUE TITLE
Plugin won't start in MacOS

### ISSUE THREAD

**Issue by tytoalba99** [JOSM/josm-gridify#8]
Under MacOS 10.9 blocked with spinning pinwheel just at selecting gridify in the menu.

**Comment by jdhoek** [comment]
The OS you use is probably irrelevant. If it is a MacOS specific issue I won't be able to reproduce it.

Can you tell me which version of JOSM and which version of Java you are using?

For the Java version you can execute `javac -version` in a terminal.

**Comment by tytoalba99** [comment]
1.8.0_241

![Captura de pantalla 2020-03-23 a las 9 10 11](https://user-images.githubusercontent.com/11778076/77295546-73d77780-6ce6-11ea-903c-905b449402ff.png)

**Comment by jdhoek** [comment]
That Java version and JOSM version should work fine. I've tried running JOSM in Spanish (`es_ES.UTF-8`), but that works too.

If you download [this jar](https://josm.openstreetmap.de/josm-tested.jar) with version 15937 of JOSM, and run it from a terminal, you might get some logging output that can help:

```
java -jar josm-tested.jar
```

You should get output that starts with this:

```
2020-03-23 09:34:33.732 INFORMACIÓN: El nivel de registro es a las INFORMACIÓN (INFO, 800)
2020-03-23 09:34:36.863 INFORMACIÓN: GET https://api.openstreetmap.org/api/0.6/user/details -> HTTP/1.1 200 (177 ms; 567 B)
2020-03-23 09:34:37.369 INFORMACIÓN: GET https://josm.openstreetmap.de/wiki/Es:StartupPage -> HTTP/1.1 200 (351 ms)
```

Do you see anything there when you reach the point where JOSM hangs?

Alternatively, you could try running the latest [development version](https://josm.openstreetmap.de/josm-latest.jar) of JOSM to see if that solves this bug.

**Comment by tytoalba99** [comment]
Having java version 1.6 also installed could cause the error?

**Comment by jdhoek** [comment]
> Having java version 1.6 also installed could cause the error?

No, that is unlikely. JOSM requires Java 8 as a minimum, and the plugins all use the same Java version.

**Comment by tytoalba99** [comment]
java -version answers
1.6.0_65

When I try   java -jar josm-tested.jar:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openstreetmap/josm/gui/MainApplication : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by jdhoek** [comment]
> java -version answers
> 1.6.0_65

Java 1.6 is not supported, so you need to run the jar with Java 1.8 (Java 8). I don't know how to update you Java installation on MacOS though.

**Comment by don-vip** [comment]
> I don't know how to update your Java installation on MacOS though.

@grischard surely knows :)

**Comment by grischard** [comment]
I think @tytoalba99 has two javas installed - the old "Apple" java, which shows up in the command line, and the more modern java 8, which is what josm uses.

**Comment by tytoalba99** [comment]
Yes, I have two javas installed in my Mac. All tasks runs ok in JOSM but gridify. I also have tried it in other mac (10.13) with only java 8 and also hanged JOSM when running gridify.

**Comment by jdhoek** [comment]
Strange, I wonder what causes this. This is the first time someone reported this. It makes me suspect that it has to with the combination of MacOS and a Spanish locale, or some other combination of factors.

Perhaps you could get the logging output on that other Mac? Or call the Java 8 `java` executable instead of the Java 6 one, but you would need to know the path it is installed in.

I don't own any Mac-hardware, and it will be a while before I physically meet up with colleagues who do have a Mac again (working from home due to the Covid-19 situation).

**Comment by tytoalba99** [comment]
hi @jdhoek I finally was able to run JOSM with java 8 terminal.

These are the log's last lines before launching gridify:

2020-03-23 22:02:43.652 INFORMACIÓN: Open file: /Volumes/Macintosh HD/Users/xxxxxx/Library/JOSM/autosave/Capa de datos 12_20200323_080454306.osm (660 bytes)
2020-03-23 22:02:44.361 INFORMACIÓN: Acción cycle-layer de barra de herramientas registrada sobreescrita: org.openstreetmap.josm.gui.dialogs.layer.CycleLayerUpAction obtiene org.openstreetmap.josm.gui.dialogs.layer.CycleLayerDownAction
2020-03-23 22:02:44.757 INFORMACIÓN: Reassigning OSX shortcut 'core_multikey:hidingFilter' from Meta to Ctrl because of conflict with ⌘+⌥+H
2020-03-23 22:02:44.758 INFORMACIÓN: Conflicto de atajo silencioso: 'core_multikey:hidingFilter' movido por 'system:hideothers' a '⌃+⌥+H'.
2020-03-23 22:02:46.109 INFORMACIÓN: Switching map mode from (none) to SelectAction


After launching gridify no more lines

**Comment by jdhoek** [comment]
Thanks. That unfortunately won't help much; I was hoping for an exception caught or something.

Just to be sure: the version of Gridify is the current one? That is:

![Screenshot from 2020-03-24 08-28-49](https://user-images.githubusercontent.com/683699/77399361-8f578680-6da9-11ea-9071-0b7d4e82ef0c.png)

**Comment by tytoalba99** [comment]
Yes, current version.
![Captura de pantalla 2020-03-24 a las 8 39 00](https://user-images.githubusercontent.com/11778076/77400240-240eb400-6dab-11ea-8a1d-8a73099056b0.png)

**Comment by grischard** [comment]
I can reproduce this on my Mac with openjdk 14. No console output, even with `--debug`, apart from this, which is most probably unrelated:

`2020-03-27 16:44:09.337 FINE: Building list of presets with name template`

Let me know if you'd like me to run any custom jar files with debugging output?

**Comment by jdhoek** [comment]
@grischard Thank, I appreciate the help.

For the moment I'm stumped though. This plugin is really quite simple in what it does in terms of code, so I'm surprised to see it fail without any output, and not seeing this behaviour with other plugins.

You are reproducing it with an English locale? So that's one variable out of the equation.

Does version [`1.2`](https://github.com/JOSM/josm-gridify/releases/tag/v1.2) of this plugin trigger the same bug? This is the previous version.

I wonder if this has something to do with my build. Perhaps I used JDK 11 instead of 8 for `1.3` by mistake? I'll have to verify that.

**Comment by tytoalba99** [comment]
Version 1.2 freeze JOSM also.
I've tried version 1.1 and it throws following error:

```
{{{
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2020-02-26 10:50:27 +0100 (Wed, 26 Feb 2020)
Build-Date:2020-02-26 09:52:41
Revision:15937
Relative:URL: ^/trunk

Identification: JOSM/1.5 (15937 es) Mac OS X 10.11.6
OS Build number: Mac OS X 10.11.6 (15G22010)
Memory Usage: 838 MB / 1820 MB (396 MB allocated, but free)
Java version: 1.8.0_241-b07, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: Display 69677504 1280x800
Maximum Screen Size: 1280x800
VM arguments: [-Djava.security.policy=file:<java.home>/lib/security/javaws.policy, -DtrustProxy=true, -Djnlpx.home=<java.home>/bin, -Djava.security.manager, -Djnlpx.origFilenameArg=${HOME}/Library/Application Support/Oracle/Java/Deployment/cache/6.0/56/1ee8cfb8-4570d2bb, -Djnlpx.remove=false, -Dsun.awt.warmup=true, -Djava.util.Arrays.useLegacyMergeSort=true, -Djnlpx.heapsize=NULL,2048m, -Dmacosx.jnlpx.dock.name=JOSM, -Dmacosx.jnlpx.dock.icon=${HOME}/Library/Application Support/Oracle/Java/Deployment/cache/6.0/25/4c122699-45f99dc4.icns, -Djnlp.application.href=https://josm.openstreetmap.de/download/josm.jnlp , -Djnlpx.jvm="<java.home>/bin/java"]
Dataset consistency test: No problems found

Plugins:
+ FastDraw (35360)
+ ImportImagePlugin (35248)
+ PicLayer (35313)
+ apache-commons (35362)
+ buildings_tools (35364)
+ contourmerge (v0.1.6)
+ editgpx (35248)
+ ejml (35122)
+ geotools (35169)
+ gridify (1526416296)
+ jaxb (35092)
+ jts (35122)
+ log4j (35092)
+ opendata (35330)
+ utilsplugin2 (35384)

Map paint styles:
- https://github.com/bastik/mapcss-tools/raw/osm/mapnik2mapcss/osm-results/mapnik.zip

Last errors/warnings:
- E: Handled by bug report queue: java.lang.NoSuchMethodError: org.openstreetmap.josm.data.osm.OsmPrimitive.getFilteredList(Ljava/util/Collection;Ljava/lang/Class;)Ljava/util/List;


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-2 (51) of javawsApplicationThreadGroup
java.lang.NoSuchMethodError: org.openstreetmap.josm.data.osm.OsmPrimitive.getFilteredList(Ljava/util/Collection;Ljava/lang/Class;)Ljava/util/List;
	at nl.jeroenhoek.josm.gridify.GridifyAction.inputDataFromSelection(GridifyAction.java:162)
	at nl.jeroenhoek.josm.gridify.GridifyAction.performGridifyAction(GridifyAction.java:95)
	at nl.jeroenhoek.josm.gridify.GridifyAction.actionPerformed(GridifyAction.java:60)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:357)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:345)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:763)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
}}}
```

**Comment by tytoalba99** [comment]
Error reported by v 1.2 :

```
{{{
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2020-02-26 10:50:27 +0100 (Wed, 26 Feb 2020)
Build-Date:2020-02-26 09:52:41
Revision:15937
Relative:URL: ^/trunk

Identification: JOSM/1.5 (15937 es) Mac OS X 10.11.6
OS Build number: Mac OS X 10.11.6 (15G22010)
Memory Usage: 856 MB / 1820 MB (378 MB allocated, but free)
Java version: 1.8.0_241-b07, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: Display 69677504 1280x800
Maximum Screen Size: 1280x800
VM arguments: [-Djava.security.policy=file:<java.home>/lib/security/javaws.policy, -DtrustProxy=true, -Djnlpx.home=<java.home>/bin, -Djava.security.manager, -Djnlpx.origFilenameArg=${HOME}/Library/Application Support/Oracle/Java/Deployment/cache/6.0/56/1ee8cfb8-4570d2bb, -Djnlpx.remove=false, -Dsun.awt.warmup=true, -Djava.util.Arrays.useLegacyMergeSort=true, -Djnlpx.heapsize=NULL,2048m, -Dmacosx.jnlpx.dock.name=JOSM, -Dmacosx.jnlpx.dock.icon=${HOME}/Library/Application Support/Oracle/Java/Deployment/cache/6.0/25/4c122699-45f99dc4.icns, -Djnlp.application.href=https://josm.openstreetmap.de/download/josm.jnlp , -Djnlpx.jvm="<java.home>/bin/java"]
Dataset consistency test: No problems found

Plugins:
+ FastDraw (35360)
+ ImportImagePlugin (35248)
+ PicLayer (35313)
+ apache-commons (35362)
+ buildings_tools (35364)
+ contourmerge (v0.1.6)
+ editgpx (35248)
+ ejml (35122)
+ geotools (35169)
+ gridify (1537118823)
+ jaxb (35092)
+ jts (35122)
+ log4j (35092)
+ opendata (35330)
+ utilsplugin2 (35384)

Map paint styles:
- https://github.com/bastik/mapcss-tools/raw/osm/mapnik2mapcss/osm-results/mapnik.zip

Last errors/warnings:
- E: Handled by bug report queue: java.lang.NoSuchMethodError: org.openstreetmap.josm.data.osm.OsmPrimitive.getFilteredList(Ljava/util/Collection;Ljava/lang/Class;)Ljava/util/List;
- E: Handled by bug report queue: java.lang.NoSuchMethodError: org.openstreetmap.josm.data.osm.OsmPrimitive.getFilteredList(Ljava/util/Collection;Ljava/lang/Class;)Ljava/util/List;


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-2 (51) of javawsApplicationThreadGroup
java.lang.NoSuchMethodError: org.openstreetmap.josm.data.osm.OsmPrimitive.getFilteredList(Ljava/util/Collection;Ljava/lang/Class;)Ljava/util/List;
	at nl.jeroenhoek.josm.gridify.GridifyAction.inputDataFromSelection(GridifyAction.java:167)
	at nl.jeroenhoek.josm.gridify.GridifyAction.performGridifyAction(GridifyAction.java:100)
	at nl.jeroenhoek.josm.gridify.GridifyAction.actionPerformed(GridifyAction.java:65)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:357)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:345)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:763)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
}}}
```

**Comment by grischard** [comment]
I'm using the en-GB locale.

**Comment by grischard** [comment]
Hi @jdhoek, I'm still happy to test any .jar with debugging output that you want to throw at me :).

**Comment by jdhoek** [comment]
@grischard Thanks! I don't know if there is any debugging I can add from within my plugin though. I did build a new version in response to another bug that may be related:

https://github.com/JOSM/josm-gridify/releases/tag/v1.3.1

Does this still fail for you?

**Comment by jdhoek** [comment]
Actually, I fixed another bug today. It is probably unrelated (this problem had a clear stack-trace, so it happened further in the code), but just in case:

https://github.com/JOSM/josm-gridify/releases/tag/v1.3.2

**Comment by tytoalba99** [comment]
v1.3.2 Didn’t work for me. Still blocks JOSM.

**Comment by jdhoek** [comment]
That's a shame.

It's a bit tedious, but to figure out if the bug is in my code or in the way the plugin is built, I've stripped the plugin down to two Java class-files that register a 'Gridify' plugin in the `more tools` menu that does nothing but show a dialog with "Test" in it:

https://github.com/JOSM/josm-gridify/releases/tag/testing-1

If this works for you, then the bug is in my code, and I can add parts of it back in until it breaks and I know where the problem lies. If this jar also fails, the problem lies in the build, and I will probably need to seek help from the JOSM developers.

Could you give this one a try?

**Comment by tytoalba99** [comment]
Test message displayed 

![Captura de pantalla 2020-05-03 a las 22 59 54](https://user-images.githubusercontent.com/11778076/80925660-f9dce880-8d91-11ea-88cb-3e694f5c07af.png)

**Comment by jdhoek** [comment]
Really? That's hopeful, it means that somewhere in my code something happens or is included that isn't working on MacOS. I'll gradually add back functionality and link the jars here so we can figure out *where* it goes wrong.

**Comment by jdhoek** [comment]
OK, this adds the short-cut (`Alt Shift Y`) and the plug-in activation criteria (needs a selection) back in:

https://github.com/JOSM/josm-gridify/releases/tag/testing-2

Does this still work?

**Comment by tytoalba99** [comment]
Worked. Same pop-up message.

**Comment by jdhoek** [comment]
OK, now what happens when I re-add all splitting functionality, but leave out the settings UI?

https://github.com/JOSM/josm-gridify/releases/tag/testing-3

This will split the selection into `2 × 3` blocks without showing you the settings dialogue.

**Comment by tytoalba99** [comment]
Worked. One converted into 6 blocks

**Comment by jdhoek** [comment]
Nice, we're getting closer then. I suspect the cause lies in one of the custom UI widgets I made for the settings dialogue. This re-adds the settings dialogue, but leaves out the three custom widgets:

https://github.com/JOSM/josm-gridify/releases/tag/testing-4

I don't know how many blocks this will give you, because it will load the last settings you used before the plugin stopped working.

**Comment by tytoalba99** [comment]
Nope. JOSM froze.

**Comment by jdhoek** [comment]
Ow? OK, first let's eliminate the settings loading/setting. This removes the UI again, but keeps the loading of the plugin's last used settings from your preferences:

https://github.com/JOSM/josm-gridify/releases/tag/testing-5

**Comment by tytoalba99** [comment]
Working again in 2x4 parts.

**Comment by jdhoek** [comment]
Good, so the problem definitely lies in the UI part. This re-adds the dialogue, with only two placeholder labels in it:

https://github.com/JOSM/josm-gridify/releases/tag/testing-6

**Comment by tytoalba99** [comment]
frozen again.

**Comment by jdhoek** [comment]
This doesn't make any sense. What happens if I strip the dialogue to the most minimal option possible?

https://github.com/JOSM/josm-gridify/releases/tag/testing-7

**Comment by jdhoek** [comment]
Another thing I've noticed is that my translations were missing from the last few versions of the plugin. The plugin is only translated in German, Dutch, and Japanese, but I wonder if the missing `en.lang` caused this problem on MacOS? Worth trying perhaps:

https://github.com/JOSM/josm-gridify/releases/tag/v1.3.3

**Comment by tytoalba99** [comment]
v1.3.3. Didn’t work either.
Test 7: Worked: 2x4 blocks.

**Comment by jdhoek** [comment]
Strange… Thanks for sticking with this issue by the way. The cause is somewhere between one line of code and the next, so it will reveal itself at some point. It just doesn't make any sense though.

This one adds only a translation of the dialogue title back in. I still suspect something weird with the translation files:

https://github.com/JOSM/josm-gridify/releases/tag/testing-8

**Comment by tytoalba99** [comment]
Test 8: Worked, output 2x4 blocks.

**Comment by jdhoek** [comment]
The difference between the failing `testing-6` and this one is minute. This adds a root-panel back in:

https://github.com/JOSM/josm-gridify/releases/tag/testing-9

**Comment by tytoalba99** [comment]
Test 9: failed

**Comment by jdhoek** [comment]
We're down to three lines of code. I've removed the `setMinimumSize` call here:

https://github.com/JOSM/josm-gridify/releases/tag/testing-10

**Comment by tytoalba99** [comment]
Test 10: OK

**Comment by jdhoek** [comment]
So this line causes the bug:

```java
setMinimumSize(new Dimension(550, 360));
```

I think I might be calling it at the wrong time?

Does the plugin work like this?

https://github.com/JOSM/josm-gridify/releases/tag/testing-11

**Comment by tytoalba99** [comment]
yes !

![Captura de pantalla 2020-05-05 a las 22 01 09](https://user-images.githubusercontent.com/11778076/81110770-4a804d00-8f1c-11ea-8d3b-841db6af3a38.png)

**Comment by tytoalba99** [comment]
A small bug. When I type the numbers in the boxes they are displayed in reverse order. i.e. if I type “2” and "0" the box shows "02”

**Comment by jdhoek** [comment]
How does this release look? This should fix that caret issue as well:

https://github.com/JOSM/josm-gridify/releases/tag/v1.4.0

### For anyone encountering this weird bug

It looks like the `setupDialog` method from JOSM's `ExtendedDialog` class should not be used to set up the dialogue. Laying out the dialogue widgets there works on GNU/Linux and Windows, but not on MacOS.

Reason unknown.

**Comment by jdhoek** [comment]
@grischard Could you confirm that the above release fixes this bug for you as well?

**Comment by tytoalba99** [comment]
Everything solved.
Thanks !
